# Blue/Green deployment configuration
blueGreen:
  enabled: true
  activeVersion: blue # flag to switch between blue and green

  blue:
    replicaCount: 2
    image:
      tag: 'v1.0.0'

  green:
    replicaCount: 2
    image:
      tag: 'latest' # New version for testing

# Single deployment (when blueGreen.enabled: false)
replicaCount: 2

image:
  # ECR URL injected via ArgoCD global values from terraform
  repository: '{{ .Values.global.ecrRepository }}'
  tag: 'latest'
  pullPolicy: Always

nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    cert-manager.io/cluster-issuer: 'selfsigned-issuer'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: webapp-tls-cert

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
