{{- if .Values.blueGreen.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thrive-webapp.fullname" . }}-blue
  labels:
    {{- include "thrive-webapp.labels" . | nindent 4 }}
    version: blue
spec:
  replicas: {{ .Values.blueGreen.blue.replicaCount }}
  selector:
    matchLabels:
      {{- include "thrive-webapp.selectorLabels" . | nindent 6 }}
      version: blue
  template:
    metadata:
      labels:
        {{- include "thrive-webapp.selectorLabels" . | nindent 8 }}
        version: blue
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.blueGreen.blue.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}